#!/usr/bin/lua

if not pcall(function()

http = require('socket.http')
url = require('socket.url')

http.USERAGENT = "ibus-sogoupycc"
keyFile = '/tmp/.sogoucloud-key'


local py, timeout, retry, key = arg[1] or 't', arg[2]
py = py:gsub("[^a-z]", '')

function refreshKey()
	local ret = http.request('http://web.pinyin.sogou.com/web_ime/patch.php') or ''
	key = ret:match('"(.-)"') or ''
	if #key > 0 then local file = io.open(keyFile, 'w') file:write(key) file:close() end
end

if not timeout then http.TIMEOUT, retry = 0.3, 7 else http.TIMEOUT, retry = timeout + 0, 1 end

-- get key
local file = io.open(keyFile, 'r')
if file then key = file:read("*line") or '' file:close() end

for attempt = 1, retry do if (not key) or (#key == 0) then http.TIMEOUT = http.TIMEOUT * 1.5 refreshKey() else break end end

function try_convert(tail, tail_len)
	local py_tail = (tail or ''):gsub(' ','')
	tail_len = tail_len or 0
	if not timeout then http.TIMEOUT, retry = 0.3, 20 else http.TIMEOUT, retry = timeout + 0, 1 end
	for attempt = 1, retry do
		-- print(attempt, http.TIMEOUT )
		local ret = http.request('http://web.pinyin.sogou.com/api/py?key='..key..'&query='..py..py_tail)
		local res = ret and ret:match('ime_callback%("(.-)"')
		if res then
			local content = url.unescape(res):match('(.-)：')
			if content and #content > 2 then
				io.write(content:sub(1, #content - 3 * tail_len))
				return 1
			else
				-- not a valid return (still HTTP200 could happen (started in Mar 19 2010, annoying!))
				return 2
			end
		end
		http.TIMEOUT = http.TIMEOUT * 1.8
		if http.TIMEOUT > 18 then break end
	end
	return 3
end

-- try various tails
for _, v in pairs{{'', 0}, {'a', 1}, {'ne', 1}, {'le', 1}, {'shi', 1}, {'hao ma', 2}, {'cai hao', 2}, {'hua shuo', 2}} do
	local r = try_convert(v[1], v[2])
	if r == 3 then break end -- timeout, network problem
	if r == 1 then return end -- success
	-- if r == 2, just go on retrying...
end

-- write smth to keep the pipe open, an ampty line indicates retrieve failure
io.write('\n')

-- mark key as invalid (delete it)
os.remove(keyFile)

end) then io.write('\n') end -- error in big pcall

-- ibus-sogoupycc-fetcher-end --
